//**********************************************************
//************** AUTOGENERATED with FLYINGDB ***************
//**********************************************************

package com.flyingboba.flyingdb;


public class PrefixLocation {

	private String locationId;
	private String streetAddress;
	private String city;
	private String state;
	private String zipcode;
	private String latitude;
	private String longitude;
	private String title;

	public PrefixLocation(String locationId, String streetAddress, String city, String state, String zipcode, String latitude, String longitude, String title) {
		setLocationId(locationId);
		setStreetAddress(streetAddress);
		setCity(city);
		setState(state);
		setZipcode(zipcode);
		setLatitude(latitude);
		setLongitude(longitude);
		setTitle(title);
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	public void setStreetAddress(String streetAddress) {
		this.streetAddress = streetAddress;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public void setState(String state) {
		this.state = state;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getLocationId() {
		return locationId;
	}

	public String getStreetAddress() {
		return streetAddress;
	}

	public String getCity() {
		return city;
	}

	public String getState() {
		return state;
	}

	public String getZipcode() {
		return zipcode;
	}

	public String getLatitude() {
		return latitude;
	}

	public String getLongitude() {
		return longitude;
	}

	public String getTitle() {
		return title;
	}

}