//**********************************************************
//************** AUTOGENERATED with FLYINGDB ***************
//**********************************************************

package com.flyingboba.flyingdb;


public class PrefixPerson {

	private String personId;
	private String firstName;
	private String lastName;
	private String email;
	private String phone;

	public PrefixPerson(String personId, String firstName, String lastName, String email, String phone) {
		setPersonId(personId);
		setFirstName(firstName);
		setLastName(lastName);
		setEmail(email);
		setPhone(phone);
	}

	public void setPersonId(String personId) {
		this.personId = personId;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getPersonId() {
		return personId;
	}

	public String getFirstName() {
		return firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public String getEmail() {
		return email;
	}

	public String getPhone() {
		return phone;
	}

}