//**********************************************************
//************** AUTOGENERATED with FLYINGDB ***************
//**********************************************************

package com.flyingboba.flyingdb;


public class PrefixEvent {

	private String eventId;
	private String date;
	private String locationId;
	private String title;

	public PrefixEvent(String eventId, String date, String locationId, String title) {
		setEventId(eventId);
		setDate(date);
		setLocationId(locationId);
		setTitle(title);
	}

	public void setEventId(String eventId) {
		this.eventId = eventId;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getEventId() {
		return eventId;
	}

	public String getDate() {
		return date;
	}

	public String getLocationId() {
		return locationId;
	}

	public String getTitle() {
		return title;
	}

}