//**********************************************************
//************** AUTOGENERATED with FLYINGDB ***************
//**********************************************************

//
// This is a sample DatabaseAdapter class.
// No updates required.
//


#import <Foundation/Foundation.h>
#import "Person.h"
#import "Event.h"
#import "Location.h"




@interface DatabaseAdapter : NSObject
{
}



+ (int) updateDeleteToDatabase: (NSString *) queryString;
+ (NSString *) insertToDatabase: (NSString *) queryString;
+ (BOOL) databaseExists;
+ (void) copyOverDatabase;
+ (NSString *) databasePath;



// -----------------------------------------------------------------------------
// Person Query Method Prototypes
// -----------------------------------------------------------------------------
+ (NSMutableArray *) getPersonListWithFieldName: (NSString*) fieldName withFieldValue: (NSString*) fieldValue withOrderBy: (NSString*) orderBy;
+ (NSString *) addPersonWithFirstName: (NSString*) aFirstName  withLastName: (NSString*) aLastName withEmail: (NSString*) aEmail withPhone: (NSString*) aPhone;
+ (int) updatePersonWithFirstName: (NSString*) aFirstName  withLastName: (NSString*) aLastName withEmail: (NSString*) aEmail withPhone: (NSString*) aPhone withFieldName: (NSString *) fieldName withFieldValue: (NSString *) fieldValue;
+ (int) removePersonWithFieldName: (NSString *) fieldName withFieldValue: (NSString *) fieldValue;

// -----------------------------------------------------------------------------
// Event Query Method Prototypes
// -----------------------------------------------------------------------------
+ (NSMutableArray *) getEventListWithFieldName: (NSString*) fieldName withFieldValue: (NSString*) fieldValue withOrderBy: (NSString*) orderBy;
+ (NSString *) addEventWithDate: (NSString*) aDate  withLocationId: (NSString*) aLocationId withTitle: (NSString*) aTitle;
+ (int) updateEventWithDate: (NSString*) aDate  withLocationId: (NSString*) aLocationId withTitle: (NSString*) aTitle withFieldName: (NSString *) fieldName withFieldValue: (NSString *) fieldValue;
+ (int) removeEventWithFieldName: (NSString *) fieldName withFieldValue: (NSString *) fieldValue;

// -----------------------------------------------------------------------------
// Location Query Method Prototypes
// -----------------------------------------------------------------------------
+ (NSMutableArray *) getLocationListWithFieldName: (NSString*) fieldName withFieldValue: (NSString*) fieldValue withOrderBy: (NSString*) orderBy;
+ (NSString *) addLocationWithStreetAddress: (NSString*) aStreetAddress  withCity: (NSString*) aCity withState: (NSString*) aState withZipcode: (NSString*) aZipcode withLatitude: (NSString*) aLatitude withLongitude: (NSString*) aLongitude withTitle: (NSString*) aTitle;
+ (int) updateLocationWithStreetAddress: (NSString*) aStreetAddress  withCity: (NSString*) aCity withState: (NSString*) aState withZipcode: (NSString*) aZipcode withLatitude: (NSString*) aLatitude withLongitude: (NSString*) aLongitude withTitle: (NSString*) aTitle withFieldName: (NSString *) fieldName withFieldValue: (NSString *) fieldValue;
+ (int) removeLocationWithFieldName: (NSString *) fieldName withFieldValue: (NSString *) fieldValue;

@end
