//**********************************************************
//************** AUTOGENERATED with FLYINGDB ***************
//**********************************************************

#import <Foundation/Foundation.h>

@interface Event : NSObject

@property (strong) NSString* eventId;
@property (strong) NSString* date;
@property (strong) NSString* locationId;
@property (strong) NSString* title;

 - (id) init;
 - (id) initWithEventId: (NSString*) paramEventId withDate: (NSString*) paramDate withLocationId: (NSString*) paramLocationId withTitle: (NSString*) paramTitle;

@end