//**********************************************************
//************** AUTOGENERATED with FLYINGDB ***************
//**********************************************************

#import "Event.h"

@implementation Event

@synthesize eventId;
@synthesize date;
@synthesize locationId;
@synthesize title;

- (id) init
{
	return [self initWithEventId: nil withDate: nil withLocationId: nil withTitle: nil];
}
 - (id) initWithEventId: (NSString*) paramEventId withDate: (NSString*) paramDate withLocationId: (NSString*) paramLocationId withTitle: (NSString*) paramTitle;
{
	self = [super init];
	if(self)
	{
		eventId = paramEventId;
		date = paramDate;
		locationId = paramLocationId;
		title = paramTitle;
	}
	return self;
}

@end