//**********************************************************
//************** AUTOGENERATED with FLYINGDB ***************
//**********************************************************

#import <Foundation/Foundation.h>

@interface Location : NSObject

@property (strong) NSString* locationId;
@property (strong) NSString* streetAddress;
@property (strong) NSString* city;
@property (strong) NSString* state;
@property (strong) NSString* zipcode;
@property (strong) NSString* latitude;
@property (strong) NSString* longitude;
@property (strong) NSString* title;

 - (id) init;
 - (id) initWithLocationId: (NSString*) paramLocationId withStreetAddress: (NSString*) paramStreetAddress withCity: (NSString*) paramCity withState: (NSString*) paramState withZipcode: (NSString*) paramZipcode withLatitude: (NSString*) paramLatitude withLongitude: (NSString*) paramLongitude withTitle: (NSString*) paramTitle;

@end