//**********************************************************
//************** AUTOGENERATED with FLYINGDB ***************
//**********************************************************

#import "Person.h"

@implementation Person

@synthesize personId;
@synthesize firstName;
@synthesize lastName;
@synthesize email;
@synthesize phone;

- (id) init
{
	return [self initWithPersonId: nil withFirstName: nil withLastName: nil withEmail: nil withPhone: nil];
}
 - (id) initWithPersonId: (NSString*) paramPersonId withFirstName: (NSString*) paramFirstName withLastName: (NSString*) paramLastName withEmail: (NSString*) paramEmail withPhone: (NSString*) paramPhone;
{
	self = [super init];
	if(self)
	{
		personId = paramPersonId;
		firstName = paramFirstName;
		lastName = paramLastName;
		email = paramEmail;
		phone = paramPhone;
	}
	return self;
}

@end