//**********************************************************
//************** AUTOGENERATED with FLYINGDB ***************
//**********************************************************

#import <Foundation/Foundation.h>

@interface Person : NSObject

@property (strong) NSString* personId;
@property (strong) NSString* firstName;
@property (strong) NSString* lastName;
@property (strong) NSString* email;
@property (strong) NSString* phone;

 - (id) init;
 - (id) initWithPersonId: (NSString*) paramPersonId withFirstName: (NSString*) paramFirstName withLastName: (NSString*) paramLastName withEmail: (NSString*) paramEmail withPhone: (NSString*) paramPhone;

@end